default['wordpress']['directorio'] = "/srv/www"
default['wordpress']['ruta_wordpress'] = "https://wordpress.org/latest.tar.gz"
default['wordpress']['archivo_wordpress'] = "latest.tar.gz"
default['wordpress']['document_root'] = "/srv/www/wordpress"
default['wordpress']['ruta_sitio_apache'] = "/etc/apache2/sites-available"
default['wordpress']['password_db'] = "Nuevo123*"
default['wordpress']['nombre_db'] = "wordpress"
default['wordpress']['usuario_db'] = "wordpress"
default['wordpress']['auth_key'] = "[G>k(Sg[|JqF)}ySi-Z_-b[gVZQBA>2!Ec4fmbV-(+= WoepYiNW[yOs><mI[(P`"
default['wordpress']['secure_auth_key'] = "wT(Z= gI!Yk<Jhm|W`Z-F:bBg*Ic|[v@RK;h?&45-?g5J}1k4mR|.@Rsf2n:D-|l"
default['wordpress']['logged_in_key'] = "orT__~N3=@z.b}sv{Cp2g~aR<BXoUAZerM).M^,n`|(4b?73?j9h_BFq/^w8}g#S"
default['wordpress']['auth_salt'] = "Tt]x7q8A|;Qn;wjENP{@*)7hfnCBznw.|o}m3w[x&hBcFv+8|({<;yKNM2I s|T,"
default['wordpress']['secure_auth_salt'] = "?4RT5 =iIVm*g:;4Z]$F8 7wft.[7?}$m|MF}p*Ux%+`W~t]|Li`G#]n~8j9>H,y"
default['wordpress']['logged_in_salt'] = "++L?8*&YC{,1/9-!FFdLMZ{%8-6,{T^Yj:;Uc[PU7NxM4`1^aZT7^zRse#v,RvC$"
default['wordpress']['nonce_salt'] = ":(*SQ<`Wo27X$1#6e^rhh^;fW%#L:BvU$cqy{p:9/a4TKpf~jBoF!#s( qCjp]l5"
default['wordpress']['url_app'] = "http://localhost:8080"
default['wordpress']['titulo_app'] = "Práctica#1 Herramientas de automatización de despliegues: Yeudi Molina"